### ISSUE TITLE
ModuleNotFoundError: No module named 'online_class'

### ISSUE THREAD

**Issue by geekymeeky** [avinashkranjan/CGS-Centralized_Grading_System#2]
(CGS-Centralized_Grading_System-master-COT32uXc) C:\Users\Srijan\Desktop\New folder\CGS-Centralized_Grading_System-master>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\commands\migrate.py", line 75, in handle
    self.check(databases=[database])
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\management\base.py", line 392, in check
    all_issues = checks.run_checks(
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Srijan\.virtualenvs\CGS-Centralized_Grading_System-master-COT32uXc\lib\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Srijan\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'online_class'

**Comment by avinashkranjan** [comment]
@geekymeeky  will Look into it..!
